# This file was generated by GoReleaser. DO NOT EDIT.
class Dynamo < Formula
  desc "dynamo is a dead-simple CLI for AWS DynamoDB"
  homepage "https://github.com/glassechidna/dynamo"
  version "0.5.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/glassechidna/dynamo/releases/download/0.5.0/dynamo_0.5.0_Darwin_x86_64.tar.gz"
    sha256 "e0db760d2757a5ce9a1236a81400f5b83be7f6fab86d93e9739a36d8e496b81c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/glassechidna/dynamo/releases/download/0.5.0/dynamo_0.5.0_Linux_x86_64.tar.gz"
      sha256 "e467b6ece997828405f1abbcb4bacf795e0e46e01a5d8f84a56e41203e494997"
    end
  end

  def install
    bin.install "dynamo"
  end
end
