# This file was generated by GoReleaser. DO NOT EDIT.
class Dynamo < Formula
  desc "dynamo is a dead-simple CLI for AWS DynamoDB"
  homepage "https://github.com/glassechidna/dynamo"
  version "0.5.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/glassechidna/dynamo/releases/download/0.5.1/dynamo_0.5.1_Darwin_x86_64.tar.gz"
    sha256 "04722ed53f231ee15d947ec9f6b1baa50bce8e8ffe020668f04b907bb1f13f8f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/glassechidna/dynamo/releases/download/0.5.1/dynamo_0.5.1_Linux_x86_64.tar.gz"
      sha256 "1ef9cb0d782485273a06d73e7c071e2e90f68bdbdb33b73be31aa9f24b35adc5"
    end
  end

  def install
    bin.install "dynamo"
  end
end
