# This file was generated by GoReleaser. DO NOT EDIT.
class Dynamo < Formula
  desc "dynamo is a dead-simple CLI for AWS DynamoDB"
  homepage "https://github.com/glassechidna/dynamo"
  version "0.7.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/glassechidna/dynamo/releases/download/0.7.0/dynamo_0.7.0_Darwin_x86_64.tar.gz"
    sha256 "ae86d73606ca9806909c3ed80ba1ae795f784bd7174c71bd35ffa7c25c6a9382"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/glassechidna/dynamo/releases/download/0.7.0/dynamo_0.7.0_Linux_x86_64.tar.gz"
      sha256 "c767c0b939fa7b0721b43bd934b0302dca0b993bda99c32def664a6f8f07ac28"
    end
  end

  def install
    bin.install "dynamo"
  end
end
