# This file was generated by GoReleaser. DO NOT EDIT.
class Ec2connect < Formula
  desc "ec2connect is a convenient SSH wrapper around EC2 instance connect"
  homepage "https://github.com/glassechidna/ec2connect"
  url "https://github.com/glassechidna/ec2connect/releases/download/0.0.1/ec2connect_0.0.1_Darwin_x86_64.tar.gz"
  version "0.0.1"
  sha256 "e8b724017dced87c886ee625a5c5c138c69116c76ea271be66927353e7fd900f"

  def install
    bin.install "ec2connect"
  end
end
