# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Efsu < Formula
  desc "efsu is for accessing AWS EFS from your machine without a VPN"
  homepage "https://github.com/glassechidna/efsu"
  version "0.4.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/glassechidna/efsu/releases/download/0.4.0/efsu_0.4.0_darwin_amd64.tar.gz"
      sha256 "8c7f40e8157296f8630634bfbf8aac5518d827ef3945cea932ebc753c708be5e"
    end
    if Hardware::CPU.arm?
      url "https://github.com/glassechidna/efsu/releases/download/0.4.0/efsu_0.4.0_darwin_arm64.tar.gz"
      sha256 "85914e05ecc0cc2e40fdc4c3551c29c003742a119758b703a7de084e752aa14e"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/glassechidna/efsu/releases/download/0.4.0/efsu_0.4.0_linux_amd64.tar.gz"
      sha256 "4345564004a2077d478bbd0a9b0de03b3d50a07735bb4373a78cd94ddfad6dc8"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/glassechidna/efsu/releases/download/0.4.0/efsu_0.4.0_linux_arm64.tar.gz"
      sha256 "13bc3a745602fc3f1c47fe51ae615696924b3b2fbeea448bb2f7bd0351cfd46d"
    end
  end

  def install
    bin.install "efsu"
  end
end
