# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Efsu < Formula
  desc "efsu is for accessing AWS EFS from your machine without a VPN"
  homepage "https://github.com/glassechidna/efsu"
  version "0.2.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/glassechidna/efsu/releases/download/0.2.1/efsu_0.2.1_darwin_amd64.tar.gz"
      sha256 "7750cd38da3cc2799491aa39d33a07e421b068e4e9a794796d00d70cb3710869"
    end
    if Hardware::CPU.arm?
      url "https://github.com/glassechidna/efsu/releases/download/0.2.1/efsu_0.2.1_darwin_arm64.tar.gz"
      sha256 "61a2fca2525a8d1bbab4ddcdf34b10bf6428de90f8bb39ea0b8e28d08381f458"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/glassechidna/efsu/releases/download/0.2.1/efsu_0.2.1_linux_amd64.tar.gz"
      sha256 "bd5b21a13106f16ff9b4e4290e6b65e32371df94f08631565389e5c7afd5317c"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/glassechidna/efsu/releases/download/0.2.1/efsu_0.2.1_linux_arm64.tar.gz"
      sha256 "56fe9f94f1c074fe23e1615d3a0b8309e91d2f22ba61d3d5efc2980ba6e47a9e"
    end
  end

  def install
    bin.install "efsu"
  end
end
