# This file was generated by GoReleaser. DO NOT EDIT.
class KmsHostKey < Formula
  desc "kms-host-key is an easy way to give all your EC2 instances SSH host certificates"
  homepage "https://github.com/glassechidna/kms-host-key"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/glassechidna/kms-host-key/releases/download/0.1.0/kms-host-key_0.1.0_darwin_amd64.tar.gz"
    sha256 "37363023da8184be933b725e631fbc5d8b91d4db4faaaa1b00f81e92921eae0e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/glassechidna/kms-host-key/releases/download/0.1.0/kms-host-key_0.1.0_linux_amd64.tar.gz"
      sha256 "deb54e8b47b28a55762f9f4c50d88cba9c15f8f70a41ef142b4e81a567663e05"
    end
  end

  def install
    bin.install "kms-host-key"
  end
end
