# This file was generated by GoReleaser. DO NOT EDIT.
class Stackit < Formula
  desc "stackit is a cross-platform CloudFormation CLI tool for easy synchronous and idempotent stack updates"
  homepage "https://github.com/glassechidna/stackit"
  url "https://github.com/glassechidna/stackit/releases/download/0.0.25/stackit_0.0.25_Darwin_x86_64.tar.gz"
  version "0.0.25"
  sha256 "9f6d1c9eb21f6f20d41e124bf031cd7cb1716e9feeecc9ad58a569e9fe3bf3bd"

  def install
    bin.install "stackit"
  end
end
