# This file was generated by GoReleaser. DO NOT EDIT.
class Webpushy < Formula
  desc "webpushy is a CLI for sending and receiving small payloads using web browser push services"
  homepage "https://github.com/glassechidna/webpushy"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/glassechidna/webpushy/releases/download/0.2.0/webpushy_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "e122fa20c75d23f69f714f1b02267dbd45179c54adad1e8f19960cd728c18f52"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/glassechidna/webpushy/releases/download/0.2.0/webpushy_0.2.0_Linux_x86_64.tar.gz"
      sha256 "50d296d85538dd423aebbc0d6d3f00ac19c65c9d39b0f940690e65054adc3bfc"
    end
  end

  def install
    bin.install "webpushy"
  end
end
