# This file was generated by GoReleaser. DO NOT EDIT.
class Webpushy < Formula
  desc "webpushy is a CLI for sending and receiving small payloads using web browser push services"
  homepage "https://github.com/glassechidna/webpushy"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/glassechidna/webpushy/releases/download/0.1.0/webpushy_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "e2d2c16085fd2f1a544c0c31ac59ea249fafbea769355e2d965754c7debb2987"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/glassechidna/webpushy/releases/download/0.1.0/webpushy_0.1.0_Linux_x86_64.tar.gz"
      sha256 "6729ecdc747b966b4d46172bd6cf41fff2b5eab73fb06464dd2dd1f4135a0374"
    end
  end

  def install
    bin.install "webpushy"
  end
end
